In [1]:
import pandas as pd

In [2]:
data_raw = pd.read_csv('data_olahan_2.csv')
data_raw

,Company,Tahun_Buku,Tanggal Rilis,kas,jumlah_aset_lancar,piutang,jumlah_aset_tidak_lancar,jumlah_aset,jumlah_liabilitas_jangka_pendek,jumlah_liabilitas_jangka_panjang,...,AR_Turnover_in_Days,Aset_Turnover,debt_to_equity,equity_ratio,debt_ratio,gpm,net_profit_margin,roa,roce,share_amount
0,BANK,2021,2022-03-31 17:47:00,2.240000e+02,2.056523e+06,1.000000e-06,1.166390e+05,2.173162e+06,4.045000e+03,8.460600e+04,...,1.006369e-08,0.016690,0.084726,0.481477,0.040794,-3.343765,-3.124679,-0.052149,-0.107234,1.450907e+10
1,LAPD,2021,2022-03-31 as:21:00,4.996100e+04,4.996100e+04,1.000000e-06,2.797800e+04,7.793900e+04,2.481495e+08,6.730610e+05,...,6.716967e-08,0.069721,-1.000313,-3191.529504,3192.529504,-19953.246780,-19961.677033,-1391.751921,0.437075,2.643982e+08
2,NICK,2021,2022-03-14 10:08:00,1.151513e+10,3.043375e+11,1.000000e-06,1.096604e+10,3.153035e+11,8.257848e+08,1.980080e+08,...,1.671185e-15,0.692691,0.003258,0.996753,0.003247,0.990364,0.990644,0.686210,0.687818,6.511500e+08
3,OASA,2021,2022-04-01 00:35:00,1.304324e+10,4.763377e+10,1.000000e-06,2.387116e+08,4.787248e+10,4.642622e+07,8.148600e+07,...,1.070136e-13,0.071247,0.002679,0.997328,0.002672,0.412715,0.391007,0.027858,0.029433,6.347220e+09
4,PLAN,2021,2022-04-30 15:28:00,1.129103e+08,1.645589e+08,1.000000e-06,8.830704e+10,8.847160e+10,2.512095e+10,1.992394e+08,...,5.538064e-14,0.074496,0.400944,0.713804,0.286196,-0.150930,-0.152438,-0.011356,-0.015702,8.928632e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2228,ZINC,2022,2023-06-26 21:49:00,5.346490e+10,6.777764e+11,4.375605e+11,1.798178e+12,2.475954e+12,7.080128e+11,9.948196e+11,...,2.226409e+02,0.289723,2.202541,0.312252,0.687748,-0.179672,-0.159128,-0.046103,-0.072902,2.525000e+10
2229,ZONE,2022,2023-04-03 15:09:00,4.910326e+09,3.747793e+11,4.837608e+10,2.770019e+11,6.517812e+11,1.991748e+11,1.057582e+11,...,2.624128e+01,1.032373,0.879154,0.532154,0.467846,0.144271,0.107514,0.110994,0.214485,8.701715e+08
2230,ZYRX,2022,2023-05-02 13:37:00,2.063763e+11,6.232536e+11,1.323574e+11,8.397621e+10,7.072298e+11,4.322842e+11,6.656257e+09,...,6.271068e+01,1.089278,1.636071,0.379352,0.620648,0.131564,0.102199,0.111323,0.368629,1.333335e+09
2231,JKSW,2020,2021-06-04 08:54:00,8.820607e+09,5.947902e+10,4.100464e+10,1.098151e+11,1.692941e+11,2.023736e+10,6.459183e+11,...,2.953282e+04,0.002993,-1.340727,-2.934902,3.934902,-17.044078,-2.234855,-0.006690,-0.057949,1.500000e+08
2232,JKSW,2022,2023-04-12 18:25:00,1.014200e+10,4.798261e+10,2.996684e+10,1.113603e+11,1.593429e+11,1.392848e+10,6.391865e+11,...,3.132903e+04,0.002191,-1.322705,-3.098801,4.098801,-26.548343,9.041484,0.019810,-0.063741,1.500000e+08

In [3]:
data_1 = data_raw[((data_raw['EPS'] >= 300) | (data_raw['EPS'] <= -300)) & (data_raw['share_amount']!= 0)]
data_2 = data_raw[((data_raw['EPS'] >= 300) | (data_raw['EPS'] <= -300)) & (data_raw['share_amount'] == 0)]
data_3 = data_raw[(data_raw['EPS'] < 300) | (data_raw['EPS'] > -300)]
data_1

,Company,Tahun_Buku,Tanggal Rilis,kas,jumlah_aset_lancar,piutang,jumlah_aset_tidak_lancar,jumlah_aset,jumlah_liabilitas_jangka_pendek,jumlah_liabilitas_jangka_panjang,...,AR_Turnover_in_Days,Aset_Turnover,debt_to_equity,equity_ratio,debt_ratio,gpm,net_profit_margin,roa,roce,share_amount
2,NICK,2021,2022-03-14 10:08:00,1.151513e+10,3.043375e+11,1.000000e-06,1.096604e+10,3.153035e+11,8.257848e+08,1.980080e+08,...,1.671185e-15,0.692691,0.003258,0.996753,0.003247,0.990364,0.990644,0.686210,0.687818,6.511500e+08
7,AALI,2020,2021-02-24 14:27:00,9.788920e+05,5.937890e+06,1.513218e+06,2.184334e+07,2.778123e+07,1.792506e+06,6.740931e+06,...,2.936796e+01,0.676969,0.443346,0.692834,0.307166,0.077771,0.024845,0.016819,0.056280,1.924688e+09
12,ACST,2020,2021-02-24 14:37:00,7.340000e+04,8.791300e+04,8.511470e+05,2.967193e+06,3.055106e+06,3.460400e+04,2.696470e+06,...,2.579385e+02,0.394235,8.428408,0.106062,0.893938,-1.114453,-1.110075,-0.437630,-0.444389,1.267516e+10
15,ADMF,2020,2021-02-18 12:43:00,7.617200e+04,5.002878e+06,2.274517e+07,2.422764e+07,2.923051e+07,1.628666e+07,5.018575e+06,...,9.386586e+02,0.302578,2.688265,0.271130,0.728870,0.166932,0.114773,0.034728,0.114065,1.000000e+08
36,AMFG,2020,2021-04-16 16:16:00,2.989810e+05,1.932986e+06,4.500070e+05,6.028671e+06,7.961657e+06,2.404568e+06,2.627252e+06,...,4.359388e+01,0.473242,1.717440,0.367993,0.632007,-0.123613,-0.127421,-0.060301,-0.083812,4.340000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125,SRTG,2022,2023-03-13 11:21:00,1.000000e+01,5.482320e+05,1.352406e+06,6.322292e+07,6.377115e+07,1.561527e+06,2.393186e+06,...,1.950856e+02,0.039678,0.066114,0.937986,0.062014,2.315391,1.812510,0.071917,0.094176,1.356484e+10
2131,STTP,2022,2023-05-04 11:39:00,2.417691e+11,2.575390e+12,5.221401e+11,2.015348e+12,4.590738e+12,5.306939e+11,1.316452e+11,...,3.864525e+01,1.074240,0.168603,0.855723,0.144277,0.153445,0.127242,0.136688,0.186383,1.310000e+09
2134,SUPR,2022,2023-03-27 08:17:00,2.361000e+03,7.279640e+05,5.251120e+05,8.873551e+06,9.601515e+06,2.145801e+06,2.874639e+06,...,1.015041e+02,0.196662,1.095909,0.477120,0.522880,0.520290,0.496161,0.097576,0.131770,7.945360e+08
2155,TGKA,2022,2023-03-27 14:55:00,5.798298e+11,3.716527e+12,1.613452e+12,4.652342e+11,4.181761e+12,1.806906e+12,3.295658e+11,...,4.537921e+01,3.103365,1.044582,0.489098,0.510902,0.046612,0.037255,0.115617,0.254713,9.184928e+08
2193,UNTR,2022,2023-02-27 18:06:00,3.828151e+07,7.893005e+07,2.030429e+07,6.154817e+07,1.404782e+08,4.203740e+07,8.926993e+06,...,5.995645e+01,0.879905,0.569347,0.637208,0.362792,0.238222,0.226917,0.199665,0.299124,2.851609e+09

In [4]:
data_1.loc[:,"EPS"]= data_1.laba_rugi_komprehensif/data_1.share_amount

In [5]:
data = pd.concat([data_1, data_2, data_3])

# Ratio Calculation

In [6]:
# Price Earning Ratio

data['per'] = data['7D_Avg'] / data['EPS']

# Current Ratio
data['current_ratio'] = data['jumlah_aset_lancar'] / data['jumlah_liabilitas_jangka_pendek']

#Quick Ratio
#data['quick_ratio'] = (data['jumlah_aset_lancar'] - data['persediaan']) / data['jumlah_liabilitas_jangka_pendek']

#Cash Ratio 
data['cash_ratio'] = data['kas'] / data['jumlah_liabilitas_jangka_pendek']

#Account Receivable Turnover
data['AR_Turnover'] = data['pendapatan']/data['piutang']

#Account Receivable Turnover in Days
data['AR_Turnover_in_Days'] = int(365) / data['AR_Turnover']

#Asset Turnover
data['Aset_Turnover'] = data['pendapatan'] / data['jumlah_aset']

#Inventory Turnover
#data['inventory_turnover'] = data['cogs'] / data['persediaan']

#deb to Equity
data['debt_to_equity'] = data['jumlah_liabilitas'] / data['jumlah_ekuitas']

#equity ratio
data['equity_ratio'] = data['jumlah_ekuitas'] / data['jumlah_aset']

#Debt Ratio --> Is it needed? even already had equity ratio?
data['debt_ratio'] = data['jumlah_liabilitas'] / data['jumlah_aset']

#Gross Profit Margin
data['gpm'] = data['laba_bruto'] / data['pendapatan']

#Net Profit Margin
data['net_profit_margin'] = data['laba_rugi_komprehensif'] / data['pendapatan']

#Return on Asset
data['roa'] = data['laba_rugi_komprehensif'] / data['jumlah_aset']

#return on Capital Employed
data['roce'] = data['laba_bruto']/(data['jumlah_ekuitas']+data['jumlah_liabilitas_jangka_panjang'])

In [7]:
data.to_csv('data_olahan_3.csv', index=False)