In [12]:
import pandas as pd

In [13]:
data_raw = pd.read_csv('data_olahan_3.csv')
data_raw

,Company,Tahun_Buku,Tanggal Rilis,kas,jumlah_aset_lancar,piutang,jumlah_aset_tidak_lancar,jumlah_aset,jumlah_liabilitas_jangka_pendek,jumlah_liabilitas_jangka_panjang,...,AR_Turnover_in_Days,Aset_Turnover,debt_to_equity,equity_ratio,debt_ratio,gpm,net_profit_margin,roa,roce,share_amount
0,NICK,2021,2022-03-14 10:08:00,1.151513e+10,3.043375e+11,1.000000e-06,1.096604e+10,3.153035e+11,8.257848e+08,1.980080e+08,...,1.671185e-15,0.692691,0.003258,0.996753,0.003247,0.990364,0.990644,0.686210,0.687818,6.511500e+08
1,AALI,2020,2021-02-24 14:27:00,9.788920e+05,5.937890e+06,1.513218e+06,2.184334e+07,2.778123e+07,1.792506e+06,6.740931e+06,...,2.936796e+01,0.676969,0.443346,0.692834,0.307166,0.077771,0.024845,0.016819,0.056280,1.924688e+09
2,ACST,2020,2021-02-24 14:37:00,7.340000e+04,8.791300e+04,8.511470e+05,2.967193e+06,3.055106e+06,3.460400e+04,2.696470e+06,...,2.579385e+02,0.394235,8.428408,0.106062,0.893938,-1.114453,-1.110075,-0.437630,-0.444389,1.267516e+10
3,ADMF,2020,2021-02-18 12:43:00,7.617200e+04,5.002878e+06,2.274517e+07,2.422764e+07,2.923051e+07,1.628666e+07,5.018575e+06,...,9.386586e+02,0.302578,2.688265,0.271130,0.728870,0.166932,0.114773,0.034728,0.114065,1.000000e+08
4,AMFG,2020,2021-04-16 16:16:00,2.989810e+05,1.932986e+06,4.500070e+05,6.028671e+06,7.961657e+06,2.404568e+06,2.627252e+06,...,4.359388e+01,0.473242,1.717440,0.367993,0.632007,-0.123613,-0.127421,-0.060301,-0.083812,4.340000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2368,ZINC,2022,2023-06-26 21:49:00,5.346490e+10,6.777764e+11,4.375605e+11,1.798178e+12,2.475954e+12,7.080128e+11,9.948196e+11,...,2.226409e+02,0.289723,2.202541,0.312252,0.687748,-0.179672,-0.159128,-0.046103,-0.072902,2.525000e+10
2369,ZONE,2022,2023-04-03 15:09:00,4.910326e+09,3.747793e+11,4.837608e+10,2.770019e+11,6.517812e+11,1.991748e+11,1.057582e+11,...,2.624128e+01,1.032373,0.879154,0.532154,0.467846,0.144271,0.107514,0.110994,0.214485,8.701715e+08
2370,ZYRX,2022,2023-05-02 13:37:00,2.063763e+11,6.232536e+11,1.323574e+11,8.397621e+10,7.072298e+11,4.322842e+11,6.656257e+09,...,6.271068e+01,1.089278,1.636071,0.379352,0.620648,0.131564,0.102199,0.111323,0.368629,1.333335e+09
2371,JKSW,2020,2021-06-04 08:54:00,8.820607e+09,5.947902e+10,4.100464e+10,1.098151e+11,1.692941e+11,2.023736e+10,6.459183e+11,...,2.953282e+04,0.002993,-1.340727,-2.934902,3.934902,-17.044078,-2.234855,-0.006690,-0.057949,1.500000e+08
2372,JKSW,2022,2023-04-12 18:25:00,1.014200e+10,4.798261e+10,2.996684e+10,1.113603e+11,1.593429e+11,1.392848e+10,6.391865e+11,...,3.132903e+04,0.002191,-1.322705,-3.098801,4.098801,-26.548343,9.041484,0.019810,-0.063741,1.500000e+08

In [14]:
data_raw = data_raw.sort_values(by=['EPS'], ascending=False)